name: Anduna CD
on: 
  push:
      branches: [ master ]
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: idlefingers/do-space-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: './public'
        SPACE_NAME: ${{ andunacicd }}
        SPACE_REGION: ${{ AMS2 }}
        SPACE_ACCESS_KEY_ID: ${{ LM2OH7SIDY45GSPWVVTW }}
        SPACE_SECRET_ACCESS_KEY: ${{ HLU+ZQJFocjESPtKNuqs74TT6RBGBxFMfLKDbF2UNiA }}
