# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build with Maven jar and RCYNC
      run: mvn clean package spring-boot:repackage
    - name: RCYNC
      run: sudo rsync -avuz -e 'ssh -i ${{secrets.PKEY}}' target/*.jar root@159.203.185.33:/
    
      
      

#     - uses: actions/checkout@master
#     - uses: idlefingers/do-space-sync-action@master
#       with:
#         args: --acl public-read
#       env:
#         SOURCE_DIR: '/home/runner/work/group-service/group-service/target'
#         SPACE_NAME: ${{ secrets.NAME }}
#         SPACE_REGION: ${{ secrets.REGION }}
#         SPACE_ACCESS_KEY_ID: ${{ secrets.KEY }}
#         SPACE_SECRET_ACCESS_KEY: ${{ secrets.SKEY }}
 
       
